name: OpenReflector
description: Amateur radio operator 2E0OPT
url: ''
baseurl: ''
author: Jon 2E0OPT
copyright: 2021-
share:
  facebook: true
  twitter: true
  gplus: false
  linkedin: false
  pinterest: false
  email: true
social:
  github: 2e0opt
  stackoverflow: null
  linkedin: null
  instagram: null
  lastfm: null
  rss: feed.xml
google_analytics_key: null
yandex_metrica: null
disqus: streetturtle
comments: false
permalink: '/:year/:month/:title/'
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true
exclude:
  - README.md
  - LICENSE
